apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-for-demo
spec:
  rules:
    http:
      paths: /blue
      - backend:
          serviceName: nginx-blue
          servicePort: 80
    http:
      paths: /green
      - backend:
          serviceName: nginx-green
          servicePort: 80
  - http:
      paths:
      - backend:
          serviceName: nginx-default
          servicePort: 80
