apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nginx-default
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - http:
      paths:
      - backend:
        serviceName: nginx-default
        servicePort: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nginx-blue
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - http:
      paths:
      - backend:
        serviceName: nginx-blue
        servicePort: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nginx-green
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - http:
      paths:
      - backend:
        serviceName: nginx-green
        servicePort: 80
