apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  replicas: ${#toInt( parameters.replicas )}
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx-default
          image: "echenarmory/nginx_default:1.1"
          ports:
            - containerPort: 80
        - name: nginx-blue
          image: "echenarmory/nginx_blue:latest"
          ports:
            - containerPort: 80
        - name: nginx-green
          image: "echenarmory/nginx_green:latest"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-default
spec: 
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: nginx-default
  sessionAffinity: None
  type: NodePort
metadata:
  name: nginx-blue
spec: 
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: nginx-blue
  sessionAffinity: None
  type: NodePort
metadata:
  name: nginx-green
spec: 
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: nginx-green
  sessionAffinity: None
  type: NodePort

